# Generated by Django 4.1.7 on 2023-08-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('price', models.FloatField()),
                ('owner', models.CharField(max_length=20)),
            ],
        ),
    ]
